name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Buildozer Cache
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: digreatbrian/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ByWhats-APK-${{ steps.get-date.outputs.date }}
        path: bin/*.apk
        
